import './globals.css'
import { AuroraBackground } from '@/components/ui/aurora-background'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AuroraBackground>
          {children}
        </AuroraBackground>
      </body>
    </html>
  )
}