import './globals.css'
import { AuroraBackground } from '@/components/ui/aurora-background'
import {Auth0Provider as UserProvider} from '@auth0/nextjs-auth0/client'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap"
        />
      </head>
      <body>
        <UserProvider>
          <AuroraBackground>
            {children}
          </AuroraBackground>
        </UserProvider>
      </body>
    </html>
  )
}